// Demo data based on your CSV file - used when no database connection available

export const demoStudents = [
  // AEM230 - Apply Clinical Practicum 1 AMB (30 students)
  { id: '1', studentId: 'H00600088', firstName: 'Abdulla', lastName: 'Mohammed Abdulrahman Saeed Almeqbaali', fullName: 'Abdulla Mohammed Abdulrahman Saeed Almeqbaali', email: 'h00600088@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '2', studentId: 'H00601780', firstName: 'Afra', lastName: 'Saeed Khassib Rashed Alsheryani', fullName: 'Afra Saeed Khassib Rashed Alsheryani', email: 'h00601780@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '3', studentId: 'H00601770', firstName: 'Shouq', lastName: 'Hamad Obaid Hamad Alshamsi', fullName: 'Shouq Hamad Obaid Hamad Alshamsi', email: 'h00601770@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '4', studentId: 'H00530541', firstName: 'Ahmed', lastName: 'Mohammed Khamis Saeed Alyahyaee', fullName: 'Ahmed Mohammed Khamis Saeed Alyahyaee', email: 'h00530541@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '5', studentId: 'H00594076', firstName: 'Alanoud', lastName: 'Salem Saeed Shenain Alnuaimi', fullName: 'Alanoud Salem Saeed Shenain Alnuaimi', email: 'h00594076@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '6', studentId: 'H00566881', firstName: 'Ali', lastName: 'Abdulla Ali Sulaiman Alameri', fullName: 'Ali Abdulla Ali Sulaiman Alameri', email: 'h00566881@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '7', studentId: 'H00599984', firstName: 'Dheyab', lastName: 'Abdallah Ali Saif Almazruii', fullName: 'Dheyab Abdallah Ali Saif Almazruii', email: 'h00599984@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '8', studentId: 'H00594033', firstName: 'Ghalya', lastName: 'Nasser Abdulrahman Nasser Al Ahbabi', fullName: 'Ghalya Nasser Abdulrahman Nasser Al Ahbabi', email: 'h00594033@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '9', studentId: 'H00594105', firstName: 'Hamad', lastName: 'Salim Hamad Mattar Alnaaimi', fullName: 'Hamad Salim Hamad Mattar Alnaaimi', email: 'h00594105@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '10', studentId: 'H00604014', firstName: 'Latifa', lastName: 'Yousef Sultan Abdulla Alshamsi', fullName: 'Latifa Yousef Sultan Abdulla Alshamsi', email: 'h00604014@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '11', studentId: 'H00601777', firstName: 'Mahra', lastName: 'Mohammed Abdulla Khamis Alshamsi', fullName: 'Mahra Mohammed Abdulla Khamis Alshamsi', email: 'h00601777@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '12', studentId: 'H00593951', firstName: 'Mahra', lastName: 'Saif Mohammed Yehal Aldhaheri', fullName: 'Mahra Saif Mohammed Yehal Aldhaheri', email: 'h00593951@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '13', studentId: 'H00601791', firstName: 'Maitha', lastName: 'Ali Mubarak Mohammed Alshamsi', fullName: 'Maitha Ali Mubarak Mohammed Alshamsi', email: 'h00601791@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '14', studentId: 'H00601746', firstName: 'Mariam', lastName: 'Mohammed Ateeq Altheeb Alshamsi', fullName: 'Mariam Mohammed Ateeq Altheeb Alshamsi', email: 'h00601746@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '15', studentId: 'H00594069', firstName: 'Mariam', lastName: 'Mohammed Khalfan Saeed Alshamsi', fullName: 'Mariam Mohammed Khalfan Saeed Alshamsi', email: 'h00594069@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '16', studentId: 'H00601795', firstName: 'Mariam', lastName: 'Obaid Hareb Obaid Alkaabi', fullName: 'Mariam Obaid Hareb Obaid Alkaabi', email: 'h00601795@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '17', studentId: 'H00601771', firstName: 'Meera', lastName: 'Mohammed Rashed Khalifa Alkaabi', fullName: 'Meera Mohammed Rashed Khalifa Alkaabi', email: 'h00601771@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '18', studentId: 'H00546028', firstName: 'Mohammed', lastName: 'Abdulla Mohammed Binreed Alsubousi', fullName: 'Mohammed Abdulla Mohammed Binreed Alsubousi', email: 'h00546028@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '19', studentId: 'H00609157', firstName: 'Mohammed', lastName: 'Khalifa Abdulla Hareb Aldhaheri', fullName: 'Mohammed Khalifa Abdulla Hareb Aldhaheri', email: 'h00609157@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '20', studentId: 'H00602802', firstName: 'Mohammed', lastName: 'Salim Abdallah Humaid Alomairi', fullName: 'Mohammed Salim Abdallah Humaid Alomairi', email: 'h00602802@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '21', studentId: 'H00571107', firstName: 'Naji', lastName: 'Mohammed Bujair Salem Alameri', fullName: 'Naji Mohammed Bujair Salem Alameri', email: 'h00571107@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '22', studentId: 'H00600056', firstName: 'Ranad', lastName: 'Sultan Khamis Khalfan Alyahyaee', fullName: 'Ranad Sultan Khamis Khalfan Alyahyaee', email: 'h00600056@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '23', studentId: 'H00594034', firstName: 'Rouda', lastName: 'Ali Khamis Ali Alkaabi', fullName: 'Rouda Ali Khamis Ali Alkaabi', email: 'h00594034@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '24', studentId: 'H00542166', firstName: 'Saeed', lastName: 'Mohammed Ali Rashed Almeqbaali', fullName: 'Saeed Mohammed Ali Rashed Almeqbaali', email: 'h00542166@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '25', studentId: 'H00594180', firstName: 'Shamma', lastName: 'Ahmed Eid Obaid Alketbi', fullName: 'Shamma Ahmed Eid Obaid Alketbi', email: 'h00594180@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '26', studentId: 'H00605422', firstName: 'Shamsa', lastName: 'Fahed Yousef Abdulla Alsawwafi', fullName: 'Shamsa Fahed Yousef Abdulla Alsawwafi', email: 'h00605422@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '27', studentId: 'H00600102', firstName: 'Sultan', lastName: 'Khulaif Ali Mohammed Alhajeri', fullName: 'Sultan Khulaif Ali Mohammed Alhajeri', email: 'h00600102@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '28', studentId: 'H00530550', firstName: 'Sultan', lastName: 'Salem Ali Ali Aljneibi', fullName: 'Sultan Salem Ali Ali Aljneibi', email: 'h00530550@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '29', studentId: 'H00502212', firstName: 'Theyab', lastName: 'Obaid Ahmed Obaid Albadi', fullName: 'Theyab Obaid Ahmed Obaid Albadi', email: 'h00502212@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },
  { id: '30', studentId: 'H00594158', firstName: 'Turfa', lastName: 'Mohammed Saif Alabed Alnuaimi', fullName: 'Turfa Mohammed Saif Alabed Alnuaimi', email: 'h00594158@hct.ac.ae', moduleId: 'aem230', module: { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)' } },

  // HEM2903 - Ambulance Practicum I (15 students)
  { id: '31', studentId: 'H00541559', firstName: 'Afra', lastName: 'Subaih Humaid Salem Al Manei', fullName: 'Afra Subaih Humaid Salem Al Manei', email: 'h00541559@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '32', studentId: 'H00467407', firstName: 'Nahyan', lastName: 'Ibrahim Abdulla Ibrahim Alblooshi', fullName: 'Nahyan Ibrahim Abdulla Ibrahim Alblooshi', email: 'h00467407@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '33', studentId: 'H00467469', firstName: 'Qmasha', lastName: 'Imad Wadee Mohammed Aldhaheri', fullName: 'Qmasha Imad Wadee Mohammed Aldhaheri', email: 'h00467469@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '34', studentId: 'H00467475', firstName: 'Aldana', lastName: 'Mohammed Manea Nasser Al Ahbabi', fullName: 'Aldana Mohammed Manea Nasser Al Ahbabi', email: 'h00467475@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '35', studentId: 'H00491386', firstName: 'Sana', lastName: 'Mohammed Nasser Gharib Al Ahbabi', fullName: 'Sana Mohammed Nasser Gharib Al Ahbabi', email: 'h00491386@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '36', studentId: 'H00491399', firstName: 'Shamayel', lastName: 'Ahmed Nashr Alsaadi', fullName: 'Shamayel Ahmed Nashr Alsaadi', email: 'h00491399@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '37', studentId: 'H00498340', firstName: 'Zayed', lastName: 'Mubarak Khamis Kharboush Almansoori', fullName: 'Zayed Mubarak Khamis Kharboush Almansoori', email: 'h00498340@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '38', studentId: 'H00510900', firstName: 'Athba', lastName: 'Saeed Ali Abed Alaryani', fullName: 'Athba Saeed Ali Abed Alaryani', email: 'h00510900@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '39', studentId: 'H00541555', firstName: 'Mahra', lastName: 'Khalifa Mohammed Khalifa Alghafli', fullName: 'Mahra Khalifa Mohammed Khalifa Alghafli', email: 'h00541555@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '40', studentId: 'H00542172', firstName: 'Talal', lastName: 'Mohammed Yousef Abdulla Alblooshi', fullName: 'Talal Mohammed Yousef Abdulla Alblooshi', email: 'h00542172@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '41', studentId: 'H00542178', firstName: 'Ahmed', lastName: 'Tareq Mohmed Ali Alhosani', fullName: 'Ahmed Tareq Mohmed Ali Alhosani', email: 'h00542178@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '42', studentId: 'H00542183', firstName: 'Shama', lastName: 'Juma Saeed Juma Alkaabi', fullName: 'Shama Juma Saeed Juma Alkaabi', email: 'h00542183@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '43', studentId: 'H00542198', firstName: 'Fatima', lastName: 'Abdulla Salem Abdulla Alkaabi', fullName: 'Fatima Abdulla Salem Abdulla Alkaabi', email: 'h00542198@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '44', studentId: 'H00542199', firstName: 'Shahd', lastName: 'Khaled Ali Mohammed Alblooshi', fullName: 'Shahd Khaled Ali Mohammed Alblooshi', email: 'h00542199@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },
  { id: '45', studentId: 'H00542939', firstName: 'Mohammed', lastName: 'Bader Nasser Abdulla Alblooshi', fullName: 'Mohammed Bader Nasser Abdulla Alblooshi', email: 'h00542939@hct.ac.ae', moduleId: 'hem2903', module: { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group' } },

  // HEM3903 - Ambulance Practicum III (8 students)
  { id: '46', studentId: 'H00459031', firstName: 'Saeed', lastName: 'Amer Salem Ahmed Alseiari', fullName: 'Saeed Amer Salem Ahmed Alseiari', email: 'h00459031@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '47', studentId: 'H00467388', firstName: 'Nahian', lastName: 'Abdullah Ali Rashed Al Saadi', fullName: 'Nahian Abdullah Ali Rashed Al Saadi', email: 'h00467388@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '48', studentId: 'H00491089', firstName: 'Bakhita', lastName: 'Saeed Rashed Hedairem Alketbi', fullName: 'Bakhita Saeed Rashed Hedairem Alketbi', email: 'h00491089@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '49', studentId: 'H00491239', firstName: 'Sherina', lastName: 'Obaid Ali Rashed Aljahoori', fullName: 'Sherina Obaid Ali Rashed Aljahoori', email: 'h00491239@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '50', studentId: 'H00491292', firstName: 'Alanood', lastName: 'Saif Jawaan Obaid Almansoori', fullName: 'Alanood Saif Jawaan Obaid Almansoori', email: 'h00491292@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '51', studentId: 'H00491322', firstName: 'Mahra', lastName: 'Abdulla Saeed Bakhit Alshebli', fullName: 'Mahra Abdulla Saeed Bakhit Alshebli', email: 'h00491322@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '52', studentId: 'H00491415', firstName: 'Shamsa', lastName: 'Salem Musabbeh Ahmed Alkaabi', fullName: 'Shamsa Salem Musabbeh Ahmed Alkaabi', email: 'h00491415@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },
  { id: '53', studentId: 'H00513261', firstName: 'Yunis', lastName: 'Maaruf', fullName: 'Yunis Maaruf', email: 'h00513261@hct.ac.ae', moduleId: 'hem3903', module: { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III' } },

  // HEM3923 - Responder Practicum I (6 students)
  { id: '54', studentId: 'H00441453', firstName: 'Abdulhamid', lastName: 'Bashar Abdulla Hasan Alhaddad', fullName: 'Abdulhamid Bashar Abdulla Hasan Alhaddad', email: 'h00441453@hct.ac.ae', moduleId: 'hem3923', module: { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I' } },
  { id: '55', studentId: 'H00459151', firstName: 'Aysha', lastName: 'Helal Humaid Anad Alkaabi', fullName: 'Aysha Helal Humaid Anad Alkaabi', email: 'h00459151@hct.ac.ae', moduleId: 'hem3923', module: { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I' } },
  { id: '56', studentId: 'H00461314', firstName: 'Fatima', lastName: 'Ali Saif Ablan Almazrouei', fullName: 'Fatima Ali Saif Ablan Almazrouei', email: 'h00461314@hct.ac.ae', moduleId: 'hem3923', module: { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I' } },
  { id: '57', studentId: 'H00461337', firstName: 'Alreem', lastName: 'Ahmed Saif Mohammed Alameri', fullName: 'Alreem Ahmed Saif Mohammed Alameri', email: 'h00461337@hct.ac.ae', moduleId: 'hem3923', module: { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I' } },
  { id: '58', studentId: 'H00490995', firstName: 'Mohammed', lastName: 'Nasser Khamis Salem Aleissaee', fullName: 'Mohammed Nasser Khamis Salem Aleissaee', email: 'h00490995@hct.ac.ae', moduleId: 'hem3923', module: { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I' } },
  { id: '59', studentId: 'H00495808', firstName: 'Elyazia', lastName: 'Jumaa Ahmad Haji', fullName: 'Elyazia Jumaa Ahmad Haji', email: 'h00495808@hct.ac.ae', moduleId: 'hem3923', module: { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I' } }
];

export const demoModules = [
  { id: 'aem230', code: 'AEM230', name: 'Apply Clinical Practicum 1 Ambulance (Diploma)', description: 'Clinical practicum for ambulance operations' },
  { id: 'hem2903', code: 'HEM2903', name: 'Ambulance 1 Practical Group', description: 'Healthcare emergency management practical training' },
  { id: 'hem3903', code: 'HEM3903', name: 'Ambulance Practicum III', description: 'Advanced ambulance practicum' },
  { id: 'hem3923', code: 'HEM3923', name: 'Responder Practicum I', description: 'First responder training practicum' }
];

export function isDemoMode(): boolean {
  return process.env.ENABLE_DEMO_MODE === 'true' || !process.env.DATABASE_URL || process.env.DATABASE_URL.includes('placeholder');
}