mutation InsertNewCourse @auth(level: USER) {
  course_insert(data: {
    academicYear: "2024-2025"
    courseCode: "CS101"
    courseName: "Introduction to Computer Science"
    semester: "Fall"
    description: "A foundational course in computer science."
    createdAt_expr: "request.time"
  })
}

query ListAllCourses @auth(level: PUBLIC) {
  courses {
    id
    academicYear
    courseCode
    courseName
    semester
    description
    createdAt
  }
}

mutation UpdateCourseDescription($id: UUID!, $description: String!) @auth(level: USER) {
  course_update(
    id: $id
    data: {
      description: $description
    }
  )
}

mutation DeleteCourse($id: UUID!) @auth(level: USER) {
  course_delete(id: $id)
}