// Complete Abu Dhabi Civil Defense Ambulance Station Codes
// Based on HCT October 2025 Schedule
// D = Day Shift (06:00 - 14:00)
// N = Night Shift (14:00 - 22:00)

export const stationCodeToLocation: Record<string, { name: string; type: string }> = {
  // Day Shifts
  'TWD': { name: 'Abu Dhabi Civil Defense - Tiwayya Station - Day Shift', type: 'ambulance_station' },
  'ZKD': { name: 'Abu Dhabi Civil Defense - Zakher Station - Day Shift', type: 'ambulance_station' },
  'MDD': { name: 'Abu Dhabi Civil Defense - Madina Station - Day Shift', type: 'ambulance_station' },
  'JMD': { name: 'Abu Dhabi Civil Defense - Jimi Station - Day Shift', type: 'ambulance_station' },
  'JHD': { name: 'Abu Dhabi Civil Defense - Jahili Station - Day Shift', type: 'ambulance_station' },
  'HLD': { name: 'Abu Dhabi Civil Defense - Hili Station - Day Shift', type: 'ambulance_station' },
  'FAD': { name: 'Abu Dhabi Civil Defense - Al Fouah Station - Day Shift', type: 'ambulance_station' },
  'FQD': { name: 'Abu Dhabi Civil Defense - Al Faqa Station - Day Shift', type: 'ambulance_station' },
  'HYD': { name: 'Abu Dhabi Civil Defense - Al Hayer Station - Day Shift', type: 'ambulance_station' },
  'DHD': { name: 'Abu Dhabi Civil Defense - Daher Station - Day Shift', type: 'ambulance_station' },
  'KHD': { name: 'Abu Dhabi Civil Defense - Khatem AlShakleh Station - Day Shift', type: 'ambulance_station' },
  'MQD': { name: 'Abu Dhabi Civil Defense - Maqam Station - Day Shift', type: 'ambulance_station' },
  'MZD': { name: 'Abu Dhabi Civil Defense - Mezyed Station - Day Shift', type: 'ambulance_station' },
  'SAD': { name: 'Abu Dhabi Civil Defense - Saad Station - Day Shift', type: 'ambulance_station' },
  'SBD': { name: 'Abu Dhabi Civil Defense - Al Shwuib Station - Day Shift', type: 'ambulance_station' },
  'SHD': { name: 'Abu Dhabi Civil Defense - Seeh AlHamah Station - Day Shift', type: 'ambulance_station' },
  'SND': { name: 'Abu Dhabi Civil Defense - Sinayeah Station - Day Shift', type: 'ambulance_station' },
  'UGD': { name: 'Abu Dhabi Civil Defense - Um Gafa Station - Day Shift', type: 'ambulance_station' },
  'SWD': { name: 'Abu Dhabi Civil Defense - Sweihan Station - Day Shift', type: 'ambulance_station' },
  'NYD': { name: 'Abu Dhabi Civil Defense - Nahyan Station - Day Shift', type: 'ambulance_station' },
  'ZHD': { name: 'Abu Dhabi Civil Defense - Zayed Station - Day Shift', type: 'ambulance_station' },

  // Night Shifts
  'TWN': { name: 'Abu Dhabi Civil Defense - Tiwayya Station - Night Shift', type: 'ambulance_station' },
  'ZKN': { name: 'Abu Dhabi Civil Defense - Zakher Station - Night Shift', type: 'ambulance_station' },
  'MDN': { name: 'Abu Dhabi Civil Defense - Madina Station - Night Shift', type: 'ambulance_station' },
  'JMN': { name: 'Abu Dhabi Civil Defense - Jimi Station - Night Shift', type: 'ambulance_station' },
  'JHN': { name: 'Abu Dhabi Civil Defense - Jahili Station - Night Shift', type: 'ambulance_station' },
  'HLN': { name: 'Abu Dhabi Civil Defense - Hili Station - Night Shift', type: 'ambulance_station' },
  'FAN': { name: 'Abu Dhabi Civil Defense - Al Fouah Station - Night Shift', type: 'ambulance_station' },
  'FQN': { name: 'Abu Dhabi Civil Defense - Al Faqa Station - Night Shift', type: 'ambulance_station' },
  'HYN': { name: 'Abu Dhabi Civil Defense - Al Hayer Station - Night Shift', type: 'ambulance_station' },
  'DHN': { name: 'Abu Dhabi Civil Defense - Daher Station - Night Shift', type: 'ambulance_station' },
  'KHN': { name: 'Abu Dhabi Civil Defense - Khatem AlShakleh Station - Night Shift', type: 'ambulance_station' },
  'MQN': { name: 'Abu Dhabi Civil Defense - Maqam Station - Night Shift', type: 'ambulance_station' },
  'MZN': { name: 'Abu Dhabi Civil Defense - Mezyed Station - Night Shift', type: 'ambulance_station' },
  'SAN': { name: 'Abu Dhabi Civil Defense - Saad Station - Night Shift', type: 'ambulance_station' },
  'SBN': { name: 'Abu Dhabi Civil Defense - Al Shwuib Station - Night Shift', type: 'ambulance_station' },
  'SHN': { name: 'Abu Dhabi Civil Defense - Seeh AlHamah Station - Night Shift', type: 'ambulance_station' },
  'SNN': { name: 'Abu Dhabi Civil Defense - Sinayeah Station - Night Shift', type: 'ambulance_station' },
  'UGN': { name: 'Abu Dhabi Civil Defense - Um Gafa Station - Night Shift', type: 'ambulance_station' },
  'SWN': { name: 'Abu Dhabi Civil Defense - Sweihan Station - Night Shift', type: 'ambulance_station' },
  'NYN': { name: 'Abu Dhabi Civil Defense - Nahyan Station - Night Shift', type: 'ambulance_station' },
  'ZHN': { name: 'Abu Dhabi Civil Defense - Zayed Station - Night Shift', type: 'ambulance_station' },

  // Short codes (2-letter without D/N suffix)
  'TW': { name: 'Abu Dhabi Civil Defense - Tiwayya Station', type: 'ambulance_station' },
  'ZK': { name: 'Abu Dhabi Civil Defense - Zakher Station', type: 'ambulance_station' },
  'MD': { name: 'Abu Dhabi Civil Defense - Madina Station', type: 'ambulance_station' },
  'JM': { name: 'Abu Dhabi Civil Defense - Jimi Station', type: 'ambulance_station' },
  'JH': { name: 'Abu Dhabi Civil Defense - Jahili Station', type: 'ambulance_station' },
  'HL': { name: 'Abu Dhabi Civil Defense - Hili Station', type: 'ambulance_station' },
  'FA': { name: 'Abu Dhabi Civil Defense - Al Fouah Station', type: 'ambulance_station' },
  'FQ': { name: 'Abu Dhabi Civil Defense - Al Faqa Station', type: 'ambulance_station' },
  'HY': { name: 'Abu Dhabi Civil Defense - Al Hayer Station', type: 'ambulance_station' },
  'DH': { name: 'Abu Dhabi Civil Defense - Daher Station', type: 'ambulance_station' },
  'KH': { name: 'Abu Dhabi Civil Defense - Khatem AlShakleh Station', type: 'ambulance_station' },
  'MQ': { name: 'Abu Dhabi Civil Defense - Maqam Station', type: 'ambulance_station' },
  'SA': { name: 'Abu Dhabi Civil Defense - Saad Station', type: 'ambulance_station' },
  'SAAD': { name: 'Abu Dhabi Civil Defense - Saad Station', type: 'ambulance_station' },
  'SB': { name: 'Abu Dhabi Civil Defense - Al Shwuib Station', type: 'ambulance_station' },
  'SH': { name: 'Abu Dhabi Civil Defense - Seeh AlHamah Station', type: 'ambulance_station' },
  'SN': { name: 'Abu Dhabi Civil Defense - Sinayeah Station', type: 'ambulance_station' },
  'UG': { name: 'Abu Dhabi Civil Defense - Um Gafa Station', type: 'ambulance_station' },
  'JIMI': { name: 'Abu Dhabi Civil Defense - Jimi Station', type: 'ambulance_station' },
  'HILI': { name: 'Abu Dhabi Civil Defense - Hili Station', type: 'ambulance_station' },
};

export const shiftCodeToTime: Record<string, { start: string; end: string }> = {
  // Day shifts: 06:00 - 14:00
  'TWD': { start: '06:00', end: '14:00' },
  'ZKD': { start: '06:00', end: '14:00' },
  'MDD': { start: '06:00', end: '14:00' },
  'JMD': { start: '06:00', end: '14:00' },
  'JHD': { start: '06:00', end: '14:00' },
  'HLD': { start: '06:00', end: '14:00' },
  'FAD': { start: '06:00', end: '14:00' },
  'FQD': { start: '06:00', end: '14:00' },
  'HYD': { start: '06:00', end: '14:00' },
  'DHD': { start: '06:00', end: '14:00' },
  'KHD': { start: '06:00', end: '14:00' },
  'MQD': { start: '06:00', end: '14:00' },
  'MZD': { start: '06:00', end: '14:00' },
  'SAD': { start: '06:00', end: '14:00' },
  'SBD': { start: '06:00', end: '14:00' },
  'SHD': { start: '06:00', end: '14:00' },
  'SND': { start: '06:00', end: '14:00' },
  'UGD': { start: '06:00', end: '14:00' },
  'SWD': { start: '06:00', end: '14:00' },
  'NYD': { start: '06:00', end: '14:00' },
  'ZHD': { start: '06:00', end: '14:00' },

  // Night shifts: 14:00 - 22:00
  'TWN': { start: '14:00', end: '22:00' },
  'ZKN': { start: '14:00', end: '22:00' },
  'MDN': { start: '14:00', end: '22:00' },
  'JMN': { start: '14:00', end: '22:00' },
  'JHN': { start: '14:00', end: '22:00' },
  'HLN': { start: '14:00', end: '22:00' },
  'FAN': { start: '14:00', end: '22:00' },
  'FQN': { start: '14:00', end: '22:00' },
  'HYN': { start: '14:00', end: '22:00' },
  'DHN': { start: '14:00', end: '22:00' },
  'KHN': { start: '14:00', end: '22:00' },
  'MQN': { start: '14:00', end: '22:00' },
  'MZN': { start: '14:00', end: '22:00' },
  'SAN': { start: '14:00', end: '22:00' },
  'SBN': { start: '14:00', end: '22:00' },
  'SHN': { start: '14:00', end: '22:00' },
  'SNN': { start: '14:00', end: '22:00' },
  'UGN': { start: '14:00', end: '22:00' },
  'SWN': { start: '14:00', end: '22:00' },
  'NYN': { start: '14:00', end: '22:00' },
  'ZHN': { start: '14:00', end: '22:00' },

  // Short codes default to day shift
  'TW': { start: '06:00', end: '14:00' },
  'ZK': { start: '06:00', end: '14:00' },
  'MD': { start: '06:00', end: '14:00' },
  'JM': { start: '06:00', end: '14:00' },
  'JH': { start: '06:00', end: '14:00' },
  'HL': { start: '06:00', end: '14:00' },
  'FA': { start: '06:00', end: '14:00' },
  'FQ': { start: '06:00', end: '14:00' },
  'HY': { start: '06:00', end: '14:00' },
  'DH': { start: '06:00', end: '14:00' },
  'KH': { start: '06:00', end: '14:00' },
  'MQ': { start: '06:00', end: '14:00' },
  'SA': { start: '06:00', end: '14:00' },
  'SAAD': { start: '06:00', end: '14:00' },
  'SB': { start: '06:00', end: '14:00' },
  'SH': { start: '06:00', end: '14:00' },
  'SN': { start: '06:00', end: '14:00' },
  'UG': { start: '06:00', end: '14:00' },
  'JIMI': { start: '06:00', end: '14:00' },
  'HILI': { start: '06:00', end: '14:00' },
};
